// Última checagem do Validador (compliance-meta). Sobrescrito a cada revisão.
window.VALIDADOR_ULTIMO = {
  exemplo: false,
  quando: '29/06/2026 (lote Direito Medico)',
  item: 'Direito Medico (Silva Pimenta) — campanha lead-gen Click-to-WhatsApp, 4 temas x 3 criativos (12 PNGs) + 4 copies. T1 processo etico CRM, T2 erro medico, T3 cirurgiao plastico/estetica, T4 publicidade medica irregular. Destino: conversa WhatsApp (11) 97716-8618, mensagem pre-preenchida termina no codigo do publico (82-85).',
  veredito: 'AJUSTAR',
  motivo: 'LOTE NAO SOBE INTEIRO COMO ESTA. 3 criativos REPROVAM e devem ser refeitos antes de subir; o resto sobe em PAUSED apos ajustes pontuais. Vereditos por peca (otica META; OAB so flag, William decide). PASSA: copy T1, copy T2; T1_v1 (jornal, nome ficticio, tem disclaimer), T1_v3 (PRAZO), T2_v2 (comparativo sozinho x defesa), T3_v3 (checklist termo, pergunta sobre documento). AJUSTAR: copy T3 ("protegem a sua carreira e patrimonio" = resultado absoluto, Misleading/Deceptive Practices Meta + promessa OAB), copy T4 (nao subir com criativos T4 atuais), T2_v1 (mock de UI real do WhatsApp = uso indevido de produto Meta + balao na 2a pessoa), T2_v3 ("mira TUDO que VOCE construiu" = Personal Attributes, insinua processo em curso contra o individuo), T3_v1 (mock de peticao judicial SEM disclaimer = Misinformation/Unacceptable Business Practices), T3_v2 ("deixa VOCE mais exposto" = Personal Attributes, baixo-medio). REPROVA (alto, refazer): T1_v2 (push falso personificando "Conselho Regional de Medicina" com "Voce recebeu uma intimacao" = simulacao de comunicacao oficial de entidade real + atributo na 2a pessoa, Misinformation + Personal Attributes); T4_v1 (mock de post do Instagram com antes/depois de silhuetas + "garantia de resultado"/"sorteio" como TEXTO renderizado = OCR do Meta le literal e nao entende ironia: alegacao proibida + estetica antes/depois + personificacao de UI do Meta); T4_v2 (pilulas grandes "ANTES E DEPOIS"/"PROMESSA DE RESULTADO" + faixa zebrada de perigo = OCR le os termos-gatilho limpos + tom de choque); T4_v3 fica em AJUSTAR-ALTO (o disclaimer "exemplo ilustrativo" salva o eixo documento falso, mas o checklist ainda renderiza "antes e depois"+"promessa ou garantia de resultado" pro OCR). ATRIBUTOS PESSOAIS: os GANCHOS de abertura (copy T1/T2/T3/T4) usam pergunta/autoidentificacao ("Medico: foi acionado?") e PASSAM; o risco esta nos elementos que AFIRMAM na 2a pessoa (push do T1_v2, "TUDO que voce construiu" do T2_v3). DESTINO/CTWA: coerencia anuncio->mensagem WhatsApp OK nos 4 temas (codigo |82-85 ja atendido). Conferir operacionalmente: numero no Ad Manager = 8618 (NAO o 7482 em analise), WABA ativa no BM correto, preview real do clique.',
  risco: 'alto',
  reescrita: 'REPROVA (refazer antes de subir): (T1_v2) descaracterizar o push: remover nome "Conselho Regional de Medicina" e a frase "Voce recebeu uma intimacao"; trocar a metafora por ampulheta/relogio sobre fundo neutro com pergunta "Medico: recebeu intimacao do CRM?" + faixa "Imagem ilustrativa". (T4_v1) eliminar a imagem antes/depois (mesmo borrada) e a UI de post do Instagram; NAO renderizar os termos literais "antes e depois"+"garantia de resultado" lado a lado; descrever a conduta sem o gatilho: "comparacoes de resultado", "promessas de cura", "sorteios de procedimento"; manter o foco em "publicidade medica fora das regras do CFM". (T4_v2) trocar as 3 pilulas literais por "Comparacoes indevidas"/"Sorteios no perfil"/"Promessas de cura"; remover a faixa zebrada de perigo (borda sobria); badge "INFRACAO ETICA" integrado ao texto. (T4_v3) manter o disclaimer e trocar os itens do checklist: "Promessa ou garantia de resultado" -> "Afirmacao de resultado certo ao paciente"; "Divulgacao de antes e depois" -> "Comparacoes de resultado". AJUSTAR: copy T3 trocar "protegem a sua carreira e o seu patrimonio" por "reduzem a exposicao da sua carreira e do seu patrimonio". copy T4 trocar "evita a dor de cabeca" por "reduz o risco de processo etico". T2_v1 estilizar baloes genericos SEM replicar a UI do WhatsApp (cor/header online/checks), rotular "conversa ilustrativa". T2_v3 trocar "mira TUDO que voce construiu" por "Uma acao de paciente pode envolver patrimonio, carreira e registro de uma vez so." T3_v1 adicionar no proprio mock a faixa "Exemplo ilustrativo. Nao representa documento oficial." (replicar o padrao que o T4_v3 ja tem). T3_v2 trocar "deixa voce mais exposto a acoes" por "aumenta a exposicao a acoes nessa especialidade". PADRAO QUE SALVA: disclaimer "Exemplo ilustrativo. Nao representa documento oficial." em TODO mock de documento (T3_v1, T1_v2) resolve o eixo Misinformation, mas NAO resolve o eixo OCR de termo-gatilho; por isso os T4 tambem precisam trocar os termos renderizados. OAB (flag, William assume risco): "analise gratuita do seu caso" (chamariz/captacao, suavizar para "avaliacao inicial do seu caso, sem compromisso"), "+20 anos / defende medicos ha mais de 20 anos" (PASSA com lastro auditavel), "protegem"/"evita a dor de cabeca" (promessa de resultado Prov. 205/2021). SUBIR EM PAUSED sempre; nao testar reprovacao na conta (reprovacao repetida penaliza account quality).',
};
